### ISSUE TITLE
Revisit TypeHint functionality and implementation

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipsesource/graphical-lsp#263] opened 2019-05-17 10:12 UTC
While testing another change, I noticed that the following stuff is either not working or not yet implemented:
- The edge type hint sent from the server regarding source and target elements is not considered, you can still connect elements as you wish.
- The repositionable attribute from the node type hint is also not considered on the client side

It probably makes sense to revisit and re-test this and create tickets for larger, missing functionality and fix minor things as part of this ticket.

**Comment by tortmayr** [comment] 2019-05-17 22:18
Possible duplicate of #162

**Closed** 2019-10-25 15:44 UTC
Labels: bug, client
